defaults:
  run: 
    working-directory: aspnet

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore
      - run: dotnet build
       
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test
       
  pack: 
    runs-on: ubuntu-20.04
    steps:
      - run: dotnet publish

on: push